# Use an official ubuntu as a parent image
# build:
#   docker build -t fastplaz .
# enter bash:
#   docker run -it fastplaz bash

FROM ubuntu:16.04 AS base

MAINTAINER Luri Darmawan <luri@***.com>

#VOLUME ["/projects/vendors", "/public_html", "/app"]
RUN mkdir -p /projects/vendors/
WORKDIR /projects
ADD ./app/ /app

# Environment
ENV NAME FastPlaz
#ENV DISTRO Ubuntu
ENV DEBIAN_FRONTEND noninteractive

# Install any needed packages specified

#RUN echo "deb http://kambing.ui.ac.id/ubuntu/ xenial main restricted universe multiverse" > /etc/apt/sources.list
#RUN echo "deb http://kambing.ui.ac.id/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list
#RUN echo "deb http://buaya.klas.or.id/ubuntu/ xenial main restricted universe multiverse" > /etc/apt/sources.list
#RUN echo "deb http://buaya.klas.or.id/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y apache2 git curl libtool
#RUN apt-get install -y apache2 git curl binutils nano build-essential
RUN apt-get install --fix-missing

#if manual install fpc
#RUN curl -O https://excellmedia.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.2/fpc_3.0.4-2_amd64.deb
#RUN curl -O https://excellmedia.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.2/fpc-src_3.0.4-2_amd64.deb
#RUN dpkg -i /app/*deb

# Apache Setup
RUN a2enmod cgi
ADD config/apache/000-default.conf /etc/apache2/sites-enabled/
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
RUN ln -s /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/
RUN echo "FastPlaz for Docker" > /var/www/html/index.html

# Make port 80 available to the world outside this container
EXPOSE 80
EXPOSE 443


# ---- Dependencies ----
#FROM base AS dependencies

# Prepare FastPlaz
RUN /app/fastplaz-init.sh
RUN ln -s /app/ubuntu-run.sh /app/run.sh
ADD ./project-examples/echo /projects/echo/
RUN ln -s /projects/echo/public_html /var/www/html/echo
RUN chmod -R 777 /projects/echo/public_html/ztemp

# run apache
CMD ["/app/run.sh"]


